name: dartby
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animations: ^2.0.11
  before_after: ^3.2.0
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.7
  flutter_bounceable: ^1.2.0
  flutter_card_swiper: ^7.0.2
  google_fonts: ^6.2.1
  iconify_flutter: ^0.0.7
  motion: ^2.0.1
  particles_flutter: ^1.0.1
  responsive_builder: ^0.7.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  video_player: ^2.9.5
  visibility_detector: ^0.4.0+2
  widget_and_text_animator: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/whatsapp.png
    - assets/images/gmail.png
    - assets/images/whatsapp2.png
    - assets/images/gmail-logo.png
    - assets/images/instagram.png
    - assets/images/back.jpg
    - assets/images/github.png
    - assets/images/linkedin.png
    - assets/images/dotby1.jpg
    - assets/images/android.png
    - assets/images/app.png
    - assets/images/logo.png
    - assets/images/IMG_3285.jpg
    - assets/images/IMG_3382.jpg
    - assets/images/styleby2.png
    - assets/images/web.png
    - assets/images/web2.png
    - assets/images/IMG_2598.jpg
    - assets/images/back.jpeg
    - assets/images/logo1.png
    - assets/images/dotby.png
    - assets/images/dotby2.png
    - assets/images/dotby3.png
    - assets/images/dotby4.png
    - assets/images/dotby5.png
    - assets/images/dotby6.png
    - assets/images/dotby7.png
    - assets/images/dotby8.png
    - assets/images/dotby9.png
    - assets/images/wm.png
    - assets/images/project.png
    - assets/images/projectm.png
    - assets/images/wd.png
    - assets/images/Mockup.png
    - assets/images/groupweb.png
    - assets/images/3d.png
    - assets/images/midnight.png
    - assets/images/midnightpc.png
    - assets/images/appstoredark.png
    - assets/images/playstoredark.png
    - assets/images/wd.jpg
    - assets/images/weatherlogo.png
    - assets/images/weatherl.png
    - assets/images/weatherlogo.jpg
    - assets/images/wmg2.png
