name: dartby
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animations: ^2.0.11
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.7
  google_fonts: ^6.2.1
  responsive_builder: ^0.7.1
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0+2
  widget_and_text_animator: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/whatsapp.png
    - assets/images/gmail.png
    - assets/images/whatsapp2.png
    - assets/images/gmail-logo.png
    - assets/images/instagram.png
    - assets/images/back.jpg
    - assets/images/github.png
    - assets/images/android.png
    - assets/images/app.jpg
    - assets/images/logo.png
    - assets/images/IMG_3285.jpg
    - assets/images/IMG_3382.jpg
    - assets/images/styleby2.png
    - assets/images/web.png
    - assets/images/IMG_2598.jpg

    